### ISSUE TITLE
Multilanguage support for docs?

### ISSUE THREAD

**Issue by GetLocalPlayer** [wurstscript/wurstscript.github.io#13]

**Comment by Frotty** [comment]
Sure, should be somewhat easily possible using this https://github.com/Anthony-Gaudino/jekyll-multiple-languages-plugin
But then we will need translators for all pages.

**Comment by GetLocalPlayer** [comment]
Isn't it better to have an opportunity to translate the docs even if the translation isn't finished yet since the docs are updated often?

**Comment by peq** [comment]
I think we can just add a warning box to the pages with incomplete translations. The box can contain a link to the English version and a plea to contribute.

**Comment by Frotty** [comment]
> Isn't it better to have an opportunity to translate the docs even if the translation isn't finished yet since the docs are updated often?

Well, which docs are you referring to? The standard library docs don't even exist in english yet :D
But yeah, for those it could work. Other parts like manual just being incomplete doesn't work imho.
Is there a language you would like to maintain?

**Comment by GetLocalPlayer** [comment]
> The standard library docs don't even exist in english yet :D

Should it not be generated automatically? From stdlib itself.
> Other parts like manual just being incomplete doesn't work imho.

At least it would be useful to let users know that Wurst is open to translation. On the main page or as a part of "Best of the Wurst" or something.
> Is there a language you would like to maintain?

Russian.

**Comment by Frotty** [comment]
> Should it not be generated automatically? From stdlib itself

hotdoc does generate some doc, but it's not in a proper format rn.
In any case it makes sense have to more detailed, informal pages to go over packages and show best practices examples next to it, since those wouldn't fit inside the package as hotdoc and it's quite common practice among frameworks.

> At least it would be useful to let users know that Wurst is open to translation. On the main page or as a part of "Best of the Wurst" or something.

sure. but since we can hardly validate usefulness and correctness of foreign translations, we would probably need maintainers for those languages to review possible PRs

**Comment by GetLocalPlayer** [comment]
> sure. but since we can hardly validate usefulness and correctness of foreign translations, we would probably need maintainers for those languages to review possible PRs

You have to start somewhere anyway. Any possible discussion here is always more than nothing. As far as I know, at least Chinese developers would be interested.

**Comment by Frotty** [comment]
> at least Chinese developers would be interested.

we offered this to the chinese ppl, but they decided to instead copy the page http://wurst.wow8.org/

**Comment by Frotty** [comment]
@GetLocalPlayer So what's the status?
Are you still interested in this?

**Comment by GetLocalPlayer** [comment]
No.
