### ISSUE TITLE
cant load prism.js

### ISSUE THREAD

**Issue by PhoenixZeng** [wurstscript/wurstscript.github.io#17]
`Failed to load resource: net::ERR_BLOCKED_BY_CLIENT`
or
`GET https://bin.wurstlang.org/prism/prism.js net::ERR_BLOCKED_BY_CLIENT`

 proxy is useless

on `bin.wurstlang.org`

**Comment by Frotty** [comment]
I'm not sure what causes this, perhaps has something to do with cloudflare?
It works for me in postman and browser, but e.g. on https://resttesttest.com/ it does the same error.

**Comment by PhoenixZeng** [comment]
maybe we can try to change the `prism.js`  to cdnjs 
e.g. `https://cdnjs.com/libraries/prism`

**Comment by Frotty** [comment]
So the rest of the page works? On resttest nothing works.

**Comment by PhoenixZeng** [comment]
i dont sure . but a part of the site is workd

**Comment by Frotty** [comment]
I replaced it with cdn link, please check again.

**Comment by PhoenixZeng** [comment]
it workd.

**Comment by Frotty** [comment]
The same now happens for the site. Maybe the version we use contains a security vulnerability or something..

**Comment by Frotty** [comment]
Nevermind, it's an easylist rule issue https://github.com/easylist/easylist/issues/3567

**Comment by PhoenixZeng** [comment]
Absolutely unexpected
