### ISSUE TITLE
Showcase

### ISSUE THREAD

**Issue by Cokemonkey11** [wurstscript/wurstscript.github.io#18]
https://www.hiveworkshop.com/threads/gargonach-0-1-0.216521/

https://www.hiveworkshop.com/threads/hunters-hall-1-6-0.164630/

https://github.com/Cokemonkey11/WurstArmorType

https://github.com/Cokemonkey11/WurstCommand

**Comment by Frotty** [comment]
image + description for each one please.

**Comment by Cokemonkey11** [comment]
![image](https://user-images.githubusercontent.com/1418966/60051269-888ccd80-96ca-11e9-96b3-30e538531d2a.png)

![image](https://user-images.githubusercontent.com/1418966/60051275-8b87be00-96ca-11e9-9d28-dc9a0de84dfd.png)

**Comment by Frotty** [comment]
The maps have been added.
The libraries need readme to be acceptable.

**Comment by Cokemonkey11** [comment]
I've added README/docs for WurstArmorType, but WurstCommand needs wurstdoktor interfaces

https://github.com/Cokemonkey11/WurstArmorType

**Comment by Frotty** [comment]
images?

**Comment by Cokemonkey11** [comment]
What sort of images go with simple libraries @Frotty ?

**Comment by Frotty** [comment]
see existing libraries

**Comment by Cokemonkey11** [comment]
![war3mapPreview](https://user-images.githubusercontent.com/1418966/62838809-dfe5fd80-bc78-11e9-8688-8c7a4b52cbd8.png)

The Gorge -> Battle Planes

**Comment by Frotty** [comment]
done
