### ISSUE TITLE
Css changes not picked up?

### ISSUE THREAD

**Issue by peq** [wurstscript/wurstscript.github.io#2]
My style changes here have not been built correctly:
https://github.com/wurstscript/wurstscript.github.io/commit/143e5a03e73b2285f8cd124f83538c68caabaa24

When I build the page on my machine with `bundle exec jekyll serve` it has the change:

> ![](http://i.imgur.com/3EUJI54.png)

But on the real page it still looks shitty:

> ![](http://i.imgur.com/t0J8wMg.png)

Any ideas?

**Comment by Frotty** [comment]
Sass doesn't seem to be properly setup (https://jekyllrb.com/docs/assets/). or you didn#t use it to generate the styles.css. Also since the site uses the styles.min.css you have to minify it as well.

Would be great to automate this, I will look into it.

**Comment by peq** [comment]
So why did it work automatically when running jekyll locally?

Can I somehow run it manually and commit the changes?
