### ISSUE TITLE
"Cascade operator" link doesn't work as expected.

### ISSUE THREAD

**Issue by lesterfan** [wurstscript/wurstscript.github.io#23]
On the manual page (https://wurstlang.org/manual.html), clicking the "Cascade operator" link on the left (under "Basic Concepts") doesn't link to the Cascade operator part of the page as expected. This may be because the link expects a section called "Cascade operator" while the actual section is entitled "Cascade operator (dot-dot-operator)".

**Comment by Frotty** [comment]
thanks
