### ISSUE TITLE
My Bounty controller system

### ISSUE THREAD

**Issue by HerlySQR** [wurstscript/wurstscript.github.io#38]
You told me that here I can share my systems, so here it is: https://github.com/HerlySQR/Bounty_Controller

**Comment by Frotty** [comment]
Yes, please provide a image and description in the fashion of the other entries https://wurstlang.org/showcase.html

**Comment by HerlySQR** [comment]
> Yes, please provide a image and description in the fashion of the other entries https://wurstlang.org/showcase.html

So a very short description and a very elaborated image? or how should be my description exactly?

**Comment by HerlySQR** [comment]
I edited the readme, but what should be a better image?

**Comment by HerlySQR** [comment]
I read this https://github.com/HerlySQR/wurstscript.github.io
but I don't understand half of that.

**Comment by Frotty** [comment]
Just put the image and a description in a comment here, I will add it to the page.

**Comment by HerlySQR** [comment]
**Bounty Controller**
![image](https://user-images.githubusercontent.com/87576302/149674441-1b0e0a13-b81f-4adb-9461-7ad348b63a91.png)
This system alows you to have control of almost everything related to the bounties (I am surprised that no one else has done this as far as I saw, I mean, I already saw other systems and none does everything that it does, and that I am not an expert and this is the first system that I share).

**Comment by Frotty** [comment]
The image should fit with the others (256x256).
I cropped it now manually and pushed the submission. Please submit correct image and description for your other submissions as well.

> (I am surprised that no one else has done this as far as I saw, I mean, I already saw other systems and none does everything that it does, and that I am not an expert and this is the first system that I share).

dunno what exactly you mean, the standard lib has default texttags for bounty, lumber, critical strike etc. as well as other texttag wrappers which seemed sufficient for everything I needed thus far.
