### ISSUE TITLE
Showcase - Ability Draft

### ISSUE THREAD

**Issue by bhusta** [wurstscript/wurstscript.github.io#5]
Hey,
ich glaube mein kleines Projekt wäre ein gutes Beispiel.
Ohne WurstScript wäre es gar nicht so leicht so etwas überhaupt zu machen.
Alle Objekte werden über die Compiletime function generiert und dann ist es noch sehr einfach durch Wurst das auf andere Maps zu übertragen.

https://www.hiveworkshop.com/threads/warcraft-3-ability-draft.291422/

**Comment by Frotty** [comment]
Hey, lange nicht gesehen :) Warst ewig nicht im channel 🌵 
Coole map, passt auf jeden Fall. Das einzige was fehlt wäre ein preview bild, hast du da was oder soll ich was von dem thread nehmen?
Und veröffentlichst du den code noch auf github oder soll ich nur den hive thread linken?
Ansonsten 👍 erste showcase submission

**Comment by bhusta** [comment]
Nehm am besten was vom Thread wegen dem Bild und darauf auch verlinken. Ich kann den code zur Zeit nicht mehr veröffentlichen. Ich hab vor einem Jahr den Code so verändert zurückgelassen, weil ich was ausprobieren wollte und jetzt müsste ich mich erstmal wieder reinarbeiten um es wieder zum laufen zu bekommen. 

Ich weiß nicht wann ich wieder aktiv modden kann. Ich sehne mich auf jeden Fall danach :)

**Comment by Frotty** [comment]
done 🍉
