### ISSUE TITLE
NativeFunctionsIO.java Dead link on the manual page

### ISSUE THREAD

**Issue by Jaccouille** [wurstscript/wurstscript.github.io#51]
There is a dead link in this section to a NativeFunctionsIO.java file: https://wurstlang.org/manual.html#functions-available-at-compiletime

https://github.com/wurstscript/wurstscript.github.io/blob/a231eac7f1ad7a996b6b52fde54bd846c4cc9e0f/_doc/manual/concepts_advanced.md?plain=1#L602

I don' knowt what this file was supposed to contain and therefore didn't look for it.
Should use git to find out where it was replaced/displaced.

**Comment by Frotty** [comment]
They were split into their own classes, I adjusted that portion of the manual, thx.
