### ISSUE TITLE
bin.wurstlang.org miss jquery now when access from china

### ISSUE THREAD

**Issue by PhoenixZeng** [wurstscript/wurstscript.github.io#9]
I hope you can use Microsoft and other CDN.
eg: 
https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.3.1.js
https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js
https://cdn.jsdelivr.net/npm/jquery@3.2.1/dist/jquery.min.js

**Comment by Frotty** [comment]
nvm, cant make issues on a fork i guess. Willfix it over the weekend.

**Comment by Frotty** [comment]
Hey @PhoenixZeng 
Sorry for taking so long!
I implemented your suggestion and the bin now uses the cloudflare cdn.
I also updated the syntax highlighting to match the one from documentation.

Cheers 🍨
